import * as THREE from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {mergeBufferGeometries} from './utils/BufferGeometryUtils.js';
import {ROUTE,STOPS,validInside,routeViolations,nearestRoute} from './navigation.mjs';
const $=s=>document.querySelector(s),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const renderer=new THREE.WebGLRenderer({canvas:$('#scene'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);
renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#c9c0af');scene.fog=new THREE.Fog('#c9c0af',45,100);
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.04,200);
const frame=new THREE.Group();frame.position.set(14.7,.35,61);frame.rotation.y=-Math.PI/2;scene.add(frame);frame.updateMatrixWorld(true);
const world=v=>frame.localToWorld(new THREE.Vector3(...v));
const hemi=new THREE.HemisphereLight('#dce9ff','#55432b',.52);scene.add(hemi);
const sun=new THREE.DirectionalLight('#ffe1ab',1.35);sun.position.copy(world([-9,16,11]));sun.target.position.copy(frame.position);scene.add(sun,sun.target);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-22,right:22,top:22,bottom:-22,near:1,far:60});sun.shadow.bias=-.00025;sun.shadow.normalBias=.02;
const pmrem=new THREE.PMREMGenerator(renderer),env=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=env.texture;pmrem.dispose();
const ground=new THREE.Mesh(new THREE.PlaneGeometry(150,150),new THREE.MeshStandardMaterial({color:'#938a76',roughness:.96}));ground.rotation.x=-Math.PI/2;ground.position.y=-.15;ground.receiveShadow=true;frame.add(ground);
const practicals=[];for(const [x,y,z]of [[0,2.75,5.8],[0,2.75,2.2],[0,2.75,-1.3],[.5,2.75,-4.2],[-1.5,2.5,7.5],[1.5,2.5,7.5]]){const light=new THREE.PointLight('#ffcf88',.65,7,1.7);light.position.set(x,y,z);frame.add(light);practicals.push(light)}
const loader=new GLTFLoader();let exterior,windowStock,interior,heroes=[],heroNodes=new Map(),colliders=[],ready=false,interiorPromise=null,lowLoaded=false;
const lod=new THREE.LOD();frame.add(lod);let stop='street',routeIndex=0,moving=false,time='day',lastInput=performance.now(),moveQueue=[],moveTarget=null,look=new THREE.Vector3(),aim=null;
let found=new Set();try{const stored=JSON.parse(localStorage.getItem('gg-v1-album')||'[]');if(Array.isArray(stored))found=new Set(stored.filter(x=>Number.isInteger(x)&&x>=1&&x<=16))}catch(e){console.warn('Album could not be restored',e.message)}
function persist(){try{localStorage.setItem('gg-v1-album',JSON.stringify([...found]))}catch(e){toast('This browser could not save the album. It will last for this visit only.')}}
function normalize(root){root.traverse(o=>{if(o.isMesh){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.envMapIntensity=.30;if(m.map)m.map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(m.transparent){m.depthWrite=false;o.castShadow=false}});o.castShadow=!mats.some(m=>m.transparent);o.receiveShadow=true}})}
// Batch static meshes by material while keeping hero roots and their extras intact.
function batch(root,preserveHeroes=false){root.updateMatrixWorld(true);const inverse=root.matrixWorld.clone().invert(),sets=new Map(),remove=[];
 root.traverse(o=>{if(!o.isMesh||Array.isArray(o.material))return;let p=o;while(p&&p!==root){if(preserveHeroes&&p.userData.heroId)return;p=p.parent}const g=o.geometry.clone();g.applyMatrix4(new THREE.Matrix4().multiplyMatrices(inverse,o.matrixWorld));for(const name of Object.keys(g.attributes))if(!['position','normal','uv'].includes(name))g.deleteAttribute(name);if(!g.attributes.normal)g.computeVertexNormals();if(!g.attributes.uv)g.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(g.attributes.position.count*2),2));if(!g.index){const index=[];for(let i=0;i<g.attributes.position.count;i++)index.push(i);g.setIndex(index)}g.clearGroups();const key=o.material.uuid;if(!sets.has(key))sets.set(key,{material:o.material,geometries:[]});sets.get(key).geometries.push(g);remove.push(o)});
 for(const o of remove)o.removeFromParent();for(const {material,geometries}of sets.values()){const g=mergeBufferGeometries(geometries,false);if(!g)throw Error('Static geometry batching failed');const mesh=new THREE.Mesh(g,material);mesh.name='Batched_'+material.name;mesh.castShadow=!material.transparent;mesh.receiveShadow=true;root.add(mesh);geometries.forEach(x=>x.dispose())}root.updateMatrixWorld(true)}
const views={front:{eye:[6.8,4.2,18.8],target:[0,3.7,2.2]},side:{eye:[-13,8.5,12],target:[0,3.3,0]},straight:{eye:[0,4.2,21],target:[0,3.7,0]},rear:{eye:[11,7,-19],target:[0,3,-1]},far:{eye:[0,12,52],target:[0,3,0]}};
function streetPose(eye,target){const centre=world(target),factor=Math.max(1,1.1/camera.aspect);camera.position.copy(centre).add(world(eye).sub(centre).multiplyScalar(factor));look.copy(centre);camera.lookAt(look)}
function view(id){const v=views[id]||views.front;camera.fov=43;camera.updateProjectionMatrix();streetPose(v.eye,v.target);moving=false;moveQueue=[];moveTarget=null;lastInput=performance.now()}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3200)}
function error(e){$('#error').hidden=false;$('#error').textContent='The shop could not complete this action: '+e.message;$('#loading').hidden=true;console.error(e)}
async function ensureInterior(){if(interior){interior.visible=true;windowStock.visible=false;return;}if(!interiorPromise){$('#enter-shop').disabled=true;$('#enter-shop').textContent='Opening the shop…';interiorPromise=(async()=>{const gltf=await loader.loadAsync('./models/interior.glb');interior=gltf.scene;normalize(interior);interior.traverse(o=>{if(o.userData.heroId&&o.type==='Object3D')heroNodes.set(Number(o.userData.heroId),o)});
 // Exporters may represent empties as Group instead of Object3D.
 interior.traverse(o=>{if(o.userData.heroId&&!o.isMesh)heroNodes.set(Number(o.userData.heroId),o)});if(heroNodes.size!==16)throw Error('Expected 16 independently modelled heroes, got '+heroNodes.size);
 for(const h of heroNodes.values())batch(h);batch(interior,true);frame.add(interior);windowStock.visible=false;frame.updateMatrixWorld(true);$('#enter-shop').disabled=false;$('#enter-shop').textContent='Step inside ↗';})().catch(e=>{interiorPromise=null;$('#enter-shop').disabled=false;error(e);throw e})}await interiorPromise}
function setInside(yes){document.body.classList.toggle('inside',yes);$('#street-card').hidden=yes;$('#rail').hidden=!yes;camera.fov=yes?62:43;camera.updateProjectionMatrix()}
function setStop(id){stop=id;$('#location').textContent=STOPS[id]?.label||'Historic High Street';document.querySelectorAll('[data-stop]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.stop===id)))}
function travel(index,target,onDone){lastInput=performance.now();aim=world(target);moveQueue=[];const step=index>=routeIndex?1:-1;for(let i=routeIndex+step;step>0?i<=index:i>=index;i+=step)moveQueue.push(i);if(!moveQueue.length)moveQueue=[index];moving=true;travel.onDone=onDone;moveTarget=null;
 if(reduced){routeIndex=index;camera.position.copy(world(ROUTE[index]));look.copy(aim);camera.lookAt(look);moving=false;moveQueue=[];travel.onDone?.();travel.onDone=null}}
async function go(id){await ensureInterior();setInside(true);if(stop==='street'){routeIndex=0;camera.position.copy(world(ROUTE[0]));look.copy(world([1.93,1.5,6]));camera.lookAt(look)}const s=STOPS[id];travel(s.index,s.look,()=>setStop(id))}
async function focus(id){await ensureInterior();setInside(true);const h=heroes.find(x=>x.id===id);if(!h)throw Error('Unknown collectible');const index=nearestRoute(h.position);if(stop==='street'){routeIndex=0;camera.position.copy(world(ROUTE[0]))}const centre=heroCentre(id);travel(index,frame.worldToLocal(centre.clone()).toArray(),()=>{setStop(Object.keys(STOPS).reduce((a,k)=>Math.abs(STOPS[k].index-index)<Math.abs(STOPS[a].index-index)?k:a,'window'));look.copy(centre);camera.lookAt(look)})}
function exit(){if(stop==='street')return;travel(0,[1.93,1.5,11],()=>{setInside(false);setStop('street');view('front');if(interior){interior.visible=false;windowStock.visible=true}})}
function heroCentre(id){const node=heroNodes.get(id);frame.updateMatrixWorld(true);return new THREE.Box3().setFromObject(node).getCenter(new THREE.Vector3())}
function projectHero(id){const v=heroCentre(id).project(camera);return[(v.x*.5+.5)*innerWidth,(-v.y*.5+.5)*innerHeight,v.z]}
function setTime(next){time=next;const night=next==='night';document.body.classList.toggle('night',night);scene.background.set(night?'#17232b':'#c9c0af');scene.fog.color.copy(scene.background);hemi.intensity=night?.19:.52;sun.intensity=night?.08:1.35;sun.color.set(night?'#a3bbdb':'#ffe1ab');practicals.forEach(l=>l.intensity=night?1.35:.65);renderer.toneMappingExposure=night?1.18:1.05;$('#time-button').textContent=night?'Daylight':'Dusk';lastInput=performance.now()}
function updateAlbum(){const n=found.size;$('#found-count').textContent=n+' / 16';$('#album-progress').textContent=n+' / 16 curiosities found';const list=$('#album-list');list.replaceChildren();heroes.forEach(h=>{const b=document.createElement('button');b.className=found.has(h.id)?'found':'';const number=document.createElement('span');number.className='album-no';number.textContent=String(h.id).padStart(2,'0');const label=document.createElement('span');label.className='album-label';label.textContent=h.name;const small=document.createElement('small');small.textContent=found.has(h.id)?'COLLECTED · INSPECT AGAIN':'YET TO BE DISCOVERED';label.append(small);b.append(number,label);b.addEventListener('click',async()=>{if(found.has(h.id)){await ensureInterior();$('#album-dialog').close();showObject(h.id,false)}else{$('#album-dialog').close();await focus(h.id);toast('Look closely. There is something here for your album.')}});list.append(b)})}
// Independent true-3D object inspector uses the same model, never a substitute thumbnail.
const ir=new THREE.WebGLRenderer({canvas:$('#object-canvas'),antialias:true,alpha:false});ir.setPixelRatio(Math.min(devicePixelRatio,1.5));ir.outputEncoding=THREE.sRGBEncoding;ir.toneMapping=THREE.ACESFilmicToneMapping;ir.toneMappingExposure=1.15;
const inspectScene=new THREE.Scene();inspectScene.background=new THREE.Color('#e5dbc6');inspectScene.environment=env.texture;inspectScene.add(new THREE.HemisphereLight('#ffffff','#746045',1));const il=new THREE.DirectionalLight('#ffe5b8',1.6);il.position.set(2,4,3);inspectScene.add(il);const ic=new THREE.PerspectiveCamera(38,1,.01,20);ic.position.set(1.2,.8,2.6);ic.lookAt(0,0,0);let inspectModel=null;
function showObject(id,isNew){const h=heroes.find(x=>x.id===id);$('#object-title').textContent=h.name;$('#object-story').textContent=h.story;$('#inspect-status').textContent=isNew?'A FIND FOR YOUR ALBUM':'FROM YOUR COLLECTION';if(inspectModel)inspectScene.remove(inspectModel);const clone=heroNodes.get(id).clone(true);clone.position.set(0,0,0);clone.rotation.set(0,0,0);clone.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(clone),centre=b.getCenter(new THREE.Vector3()),size=b.getSize(new THREE.Vector3());clone.position.sub(centre);inspectModel=new THREE.Group();inspectModel.add(clone);inspectModel.scale.setScalar(1.2/Math.max(size.x,size.y,size.z));inspectScene.add(inspectModel);$('#inspect-dialog').showModal();resizeInspector();ir.render(inspectScene,ic);lastInput=performance.now()}
function resizeInspector(){const r=$('#object-canvas').getBoundingClientRect();if(!r.width)return;ir.setSize(r.width,r.height,false);ic.aspect=r.width/r.height;ic.updateProjectionMatrix()}
function collect(id){const fresh=!found.has(id);found.add(id);persist();updateAlbum();showObject(id,fresh)}
$('#close-inspect').onclick=()=>$('#inspect-dialog').close();$('#close-album').onclick=()=>$('#album-dialog').close();$('#album-button').onclick=()=>{updateAlbum();$('#album-dialog').showModal();lastInput=performance.now()};$('#time-button').onclick=()=>setTime(time==='day'?'night':'day');$('#enter-shop').onclick=()=>go('window').catch(error);$('#exit-shop').onclick=exit;
$('#hint-button').onclick=()=>{const h=heroes.find(h=>!found.has(h.id));if(h)focus(h.id).then(()=>toast('A little clue: '+h.name.toLowerCase()+'.')).catch(error);else toast('Every curiosity has a place in your album. Thank you for visiting.')};
for(const [id,s]of Object.entries(STOPS)){const b=document.createElement('button');b.textContent={window:'Window',gallery:'Tables',cabinets:'Cabinets',collector:'Collector',counter:'Counter'}[id];b.dataset.stop=id;b.onclick=()=>go(id).catch(error);$('#stops').append(b)}
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();let pointer=null;
$('#scene').addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,drag:0};lastInput=performance.now();$('#scene').setPointerCapture(e.pointerId)});
$('#scene').addEventListener('pointermove',e=>{if(!pointer)return;const dx=e.clientX-pointer.lastX,dy=e.clientY-pointer.lastY;pointer.drag+=Math.abs(dx)+Math.abs(dy);pointer.lastX=e.clientX;pointer.lastY=e.clientY;if(pointer.drag<6)return;lastInput=performance.now();if(stop==='street'){const target=world([0,3.4,1.5]),v=camera.position.clone().sub(target);const sph=new THREE.Spherical().setFromVector3(v);sph.theta-=dx*.005;sph.phi=THREE.MathUtils.clamp(sph.phi+dy*.003,.55,1.45);camera.position.copy(target).add(new THREE.Vector3().setFromSpherical(sph));look.copy(target)}else{const dir=look.clone().sub(camera.position);const sph=new THREE.Spherical().setFromVector3(dir);sph.theta-=dx*.004;sph.phi=THREE.MathUtils.clamp(sph.phi+dy*.003,.5,2.35);look.copy(camera.position).add(new THREE.Vector3().setFromSpherical(sph))}camera.lookAt(look)});
$('#scene').addEventListener('pointerup',e=>{const click=pointer&&pointer.drag<6;pointer=null;if(!click||moving||stop==='street')return;mouse.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects([...heroNodes.values()],true);if(hits.length){let node=hits[0].object;while(node&&!node.userData.heroId)node=node.parent;if(node)collect(Number(node.userData.heroId))}});
let ip=null;$('#object-canvas').addEventListener('pointerdown',e=>{ip=[e.clientX,e.clientY];$('#object-canvas').setPointerCapture(e.pointerId)});$('#object-canvas').addEventListener('pointermove',e=>{if(ip&&inspectModel){inspectModel.rotation.y+=(e.clientX-ip[0])*.012;inspectModel.rotation.x+=(e.clientY-ip[1])*.008;ip=[e.clientX,e.clientY]}});$('#object-canvas').addEventListener('pointerup',()=>ip=null);
addEventListener('keydown',e=>{if($('#inspect-dialog').open||$('#album-dialog').open)return;if(e.key==='ArrowUp'||e.key==='w'){e.preventDefault();if(stop==='street')go('window').catch(error);else go(Object.keys(STOPS)[Math.min(4,Object.keys(STOPS).indexOf(stop)+1)]).catch(error)}if(e.key==='ArrowDown'||e.key==='s'){e.preventDefault();const i=Object.keys(STOPS).indexOf(stop);if(i>0)go(Object.keys(STOPS)[i-1]).catch(error);else exit()}});
function inspect(){const textureMaterials=new Set();let meshes=0,texturedMeshes=0,triangles=0;[exterior,interior,windowStock].filter(Boolean).forEach(root=>root.traverse(o=>{if(o.isMesh){meshes++;if(o.material.map){texturedMeshes++;textureMaterials.add(o.material.name)}triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3}}));return{textureMaterials:[...textureMaterials],interiorVisible:!!interior?.visible,windowVisible:!!windowStock?.visible,meshes,texturedMeshes,triangles,drawCalls:renderer.info.render.calls,placement:frame.position.toArray(),heroCount:heroNodes.size,lodLevel:lod.getCurrentLevel(),lowLoaded,interiorLoaded:!!interior}}
function frontBounds(){const points=[];for(const x of [-2.9,2.9])for(const y of [0,9.3]){const p=world([x,y,7.3]).project(camera);points.push([(p.x*.5+.5)*innerWidth,(-p.y*.5+.5)*innerHeight])}return points}
window.GG={frontBounds,get ready(){return ready},inspect,view,focus,projectHero,hero:id=>heroes.find(h=>h.id===id),routeViolations:()=>routeViolations(colliders),state:()=>({stop,moving,interiorLoaded:!!interior,heroCount:heroNodes.size,found:[...found],time}),setTime};
try{const [g,h,c]=await Promise.all([loader.loadAsync('./models/exterior.glb'),fetch('./data/heroes.json').then(r=>{if(!r.ok)throw Error('Hero data missing');return r.json()}),fetch('./data/collision.json').then(r=>r.json())]);exterior=g.scene;normalize(exterior);batch(exterior);lod.addLevel(exterior,0);heroes=h;colliders=c;if(routeViolations(colliders).length)throw Error('The authored route intersects furniture');const w=await loader.loadAsync('./models/window.glb');windowStock=w.scene;normalize(windowStock);batch(windowStock);frame.add(windowStock);updateAlbum();ready=true;$('#loading').hidden=true;view('front');loader.loadAsync('./models/exterior-lod.glb').then(g=>{normalize(g.scene);batch(g.scene);lod.addLevel(g.scene,35);lowLoaded=true}).catch(e=>console.warn('Distant LOD unavailable; retaining detailed model',e.message))}catch(e){error(e)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(stop==='street')view('front');resizeInspector()});
let last=performance.now();const frameTimes=[];
renderer.setAnimationLoop(t=>{const dt=Math.min(.06,(t-last)/1000);last=t;if(ready){if(moving&&!reduced){if(!moveTarget&&moveQueue.length){const i=moveQueue.shift();moveTarget={index:i,point:world(ROUTE[i])}}if(moveTarget){const delta=moveTarget.point.clone().sub(camera.position),distance=delta.length(),step=dt*2.4;if(distance<=step){camera.position.copy(moveTarget.point);routeIndex=moveTarget.index;moveTarget=null}else camera.position.addScaledVector(delta,step/distance);look.lerp(aim,Math.min(1,dt*6));camera.lookAt(look)}if(!moveTarget&&!moveQueue.length){moving=false;look.copy(aim);camera.lookAt(look);travel.onDone?.();travel.onDone=null}}if(interior&&stop!=='street')interior.visible=true;
 if(stop==='street'&&!moving&&!reduced&&performance.now()-lastInput>10000){const a=Math.sin(t*.00009)*.10;streetPose([6.8+Math.sin(a)*4,4.2,18.8],[0,3.7,2.2])}
 lod.update(camera);renderer.render(scene,camera);if($('#inspect-dialog').open){if(inspectModel&&!ip&&!reduced)inspectModel.rotation.y+=dt*.16;ir.render(inspectScene,ic)}if(frameTimes.length<240&&dt>0)frameTimes.push(dt*1000)}});
window.GG.performance=()=>({samples:frameTimes.length,meanMs:frameTimes.reduce((a,b)=>a+b,0)/Math.max(1,frameTimes.length)});
